spring:
  application:
    name: config-client
    boot:
      admin:
        client:
          url: http://localhost:8669
  #
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest
#
server:
  port: 8667
#
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  #    prefer-ip-address: true

  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
##  ---------------------
##  作者：方志朋
##  来源：CSDN
##  原文：https://blog.csdn.net/forezp/article/details/86105850
##  版权声明：本文为博主原创文章，转载请附上博文链接！